import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import NewsletterSignup from '../components/NewsletterSignupForm/NewsletterSignup'
import LandingPageLogo from '../components/LandingPageLogo/LandingPageLogo'
import { getClasses } from '../styles/IndexPage.jss'

const Home: NextPage = () => {
  const classes = getClasses()
  return (
    <div className={styles.container}>
      <Head>
        <title>Signup for our Newsletter | Mímir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <LandingPageLogo />
        <div className={styles['content-container']}>
          {/* Info text */}
          <p className={styles.infotext}>Let’s work together to create less division. Filling out this form will take less than one-minute, and will give us important product development information. The first 500 people to fill out the form will have access to our premium product for free, for life. Thank you very much.</p>
          {/* Signup form */}
          <NewsletterSignup />
        </div>
      </main>

      <footer className={styles.footer}>
          Coming in 2023
      </footer>
    </div>
  )
}

export default Home
